name: License check
on: pull_request

env:
  ALLOWED_LICENSES: >
    MIT;
    BSD;
    ISC;
    Apache-2.0;
    MPL-2.0;
    LGPL-3.0;
    LGPL-3.0-or-later;
    CC0-1.0;
    CC-BY-3.0;
    CC-BY-4.0;
    Python-2.0;
    PSF;
    Public Domain;
    WTFPL;
    Unlicense;
    BlueOak-1.0.0;
  # It has to be one line, there must be no space between packages.
  EXCLUDE_PACKAGES: testrpc@0.0.1;uuid@2.0.1;@cspell/dict-en-common-misspellings@2.0.0;

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: EmbarkStudios/cargo-deny-action@8371184bd11e21dcf8ac82ebf8c9c9f74ebf7268 # v2.0.1
      working-directory: api
      with:
        command: check
        command-arguments: "--hide-inclusion-graph"
  
  js-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm license-checker

      - name: Install dependencies
        working-directory: plugin
        run: pnpm install

      - name: Check licenses
        working-directory: plugin
        run: npx license-checker --json --onlyAllow="$ALLOWED_LICENSES" --excludePackages "$EXCLUDE_PACKAGES" --excludePrivatePackages
